# Assignment 3

### 11/11/2020

### Question 1

In [1]:
import numpy as np  #Importing Numpy module

npArray = np.arange(2,51,3)
print(npArray)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


### Question 2

In [2]:
npArray1,npArray2 = (list(map(int,input().split())) for i in range(2))

npArray1 = np.array(npArray1)
npArray2 = np.array(npArray2)

print(np.concatenate((npArray1,npArray2)))  #Concating 2 Arrays

print(np.sort(np.concatenate((npArray1,npArray2))))  #Sorting the concated Array

10 20 30 40
7 8 9 0
[10 20 30 40  7  8  9  0]
[ 0  7  8  9 10 20 30 40]


### Question 3

In [3]:
npArray = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])

print('Shape is :- ' + str(npArray.shape))
print('Size is :- ' + str(npArray.size))

Shape is :- (3, 3)
Size is :- 9


### Question 4

In order to convert 1D array to 2D array, we make use of numpy.reshape()
##### Syntax :- numpy.reshape(a, newshape)

In [4]:
npArray = np.array([ [1,2,3,4,5,6,7,8,9] ])
print(npArray,npArray.shape) 

npArray = npArray.reshape(3,3) 
print(npArray,npArray.shape)

print("\n USING NEWAXIS")
arry=np.random.rand(5,)
print(arry.ndim)
newArr = arry[np.newaxis, :]
print(newArr.ndim)

[[1 2 3 4 5 6 7 8 9]] (1, 9)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)

 USING NEWAXIS
1
2


### Question 5

In [5]:
npArray1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
npArray2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])

print(np.vstack((npArray1,npArray2))) #row-wise sequence
print() 
print(np.hstack((npArray1,npArray2))) #column-wise sequence

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]

[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


### Question 6

In [6]:
npArray = np.array([1,5,6,9,8,2,6,8,52,6,7,8,0,2,0,8,9,3,2,87,1])
print(np.unique(npArray,return_counts=True))

(array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 52, 87]), array([2, 2, 3, 1, 1, 3, 1, 4, 2, 1, 1], dtype=int64))
